---
- name: How to prompt fo rvariables
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "yourpassword" # variable name to define
      prompt: "What is your password:" # question to ask
      ## do not reveal the password (optional)
      private: yes
      ## run this encrpytion method (option)
      encrypt: "sha512_crypt"
      # type the passwor dtwice (opitonal)
      confirm: yes
      ## this is the size of the RAND you'd like to have generated (optional)
      salt_size: 7
      # salt: slappysquirrel88 # provide your own RAND (optional)
      # default to this password (optional)
      default: 'querty'


  tasks:
    - name: Print out the password
      debug:
        msg: "{{ yourpassword }}"
