---
- name: Another network playbook example
  hosts: aristaswitchessecure
  gather_facts: no
  vars_files:
    - vault.yml

  tasks:
  - name: Harvist Arista facts
    eos_facts:
    when: ansible_network_os == 'eos'
